/* eslint-disable no-console */
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parse } from '@formatjs/icu-messageformat-parser';
import { loadConfig, findNamespaces, readNamespaceMessages, ensureDir } from './utils.js';
import { extractParams } from './parse.js';
import type { CliConfig } from './types.js';

export async function generate(cwd: string, config?: Partial<CliConfig>): Promise<void> {
  const resolved = { ...(await loadConfig(cwd)), ...config };
  const { defaultLocale, localesDir, outputDir, precompile = true } = resolved;

  await ensureDir(outputDir);

  const namespaces = await findNamespaces(localesDir, defaultLocale);
  const namespaceData: Record<string, Record<string, string>> = {};

  for (const namespace of namespaces) {
    namespaceData[namespace] = await readNamespaceMessages(localesDir, defaultLocale, namespace);
  }

  // Generate types
  const typesContent = generateTypes(namespaceData);
  await writeFile(join(outputDir, 'messages.d.ts'), typesContent);

  // Generate key constants
  const keysContent = generateKeys(namespaceData);
  await writeFile(join(outputDir, 'keys.ts'), keysContent);

  // Generate precompiled messages if enabled
  if (precompile) {
    const precompiled = generatePrecompiled(namespaceData);
    await writeFile(join(outputDir, 'messages.ts'), precompiled);
  }

  console.log(`Generated i18n types in ${outputDir}`);
}

function generateTypes(namespaceData: Record<string, Record<string, string>>): string {
  const namespaceTypes = Object.entries(namespaceData).map(([namespace, messages]) => {
    const keys = Object.keys(messages)
      .map((key) => `    '${key}': Message;`)
      .join('\n');
    return `  '${namespace}': {\n${keys}\n  } & Record<string, Message>;`;
  });

  const paramTypes = Object.entries(namespaceData).map(([namespace, messages]) => {
    const keys = Object.entries(messages)
      .map(([key, value]) => {
        const params = extractParams(value);
        const paramType = params.length
          ? `{ ${params.map((p) => `${p}: string | number | Date`).join('; ')} }`
          : 'Record<string, never>';
        return `    '${namespace}.${key}': ${paramType};`;
      })
      .join('\n');
    return keys;
  });

  return `// This file is auto-generated by @fly4react/i18n-cli. Do not edit manually.

import type { Message } from '@fly4react/i18n-core';

export interface Messages {
${namespaceTypes.join('\n')}
  [key: string]: Record<string, Message>;
}

export type TranslationParams = {
${paramTypes.join('\n')}
};

export type Namespace = keyof Messages;

export type MessageKey<N extends Namespace = Namespace> = keyof Messages[N] & string;

declare global {
  interface Fly4ReactI18nMessages extends Messages {}
  interface Fly4ReactI18nParams extends TranslationParams {}
}
`;
}

function generateKeys(namespaceData: Record<string, Record<string, string>>): string {
  const lines: string[] = [
    '// This file is auto-generated by @fly4react/i18n-cli. Do not edit manually.',
    '',
    'export const keys = {',
  ];

  for (const [namespace, messages] of Object.entries(namespaceData)) {
    lines.push(`  ${namespace}: {`);
    for (const key of Object.keys(messages)) {
      const constName = key.replace(/\./g, '_');
      lines.push(`    ${constName}: '${key}' as const,`);
    }
    lines.push('  },');
  }

  lines.push('} as const;');
  lines.push('');
  return lines.join('\n');
}

function generatePrecompiled(namespaceData: Record<string, Record<string, string>>): string {
  const lines: string[] = [
    '// This file is auto-generated by @fly4react/i18n-cli. Do not edit manually.',
    "import type { Messages, TranslationParams } from './messages.d.js';",
    '',
    'export type { Messages, TranslationParams };',
    '',
    'export const messages: Messages = {',
  ];

  for (const [namespace, messages] of Object.entries(namespaceData)) {
    lines.push(`  ${namespace}: {`);
    for (const [key, value] of Object.entries(messages)) {
      const ast = JSON.stringify(parse(value));
      lines.push(`    ${key}: ${ast},`);
    }
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');
  return lines.join('\n');
}
